In [22]:
import numpy as np

X = np.array([[5, 3, 6]])
W = np.array([[2, 1, 4, 3], [0, 5, 3, 1], [2, 5, 4, 0]])

Y = X @ W

print("X.shape", X.shape)
print("W.shape", W.shape)
print("Y.shape", Y.shape)
X, W, Y

X.shape (1, 3)
W.shape (3, 4)
Y.shape (1, 4)


(array([[5, 3, 6]]),
 array([[2, 1, 4, 3],
        [0, 5, 3, 1],
        [2, 5, 4, 0]]),
 array([[22, 50, 53, 18]]))

In [23]:
YT = W.T @ X.T

print("X.T.shape", X.T.shape)
print("W.T.shape", W.T.shape)
print("YT.shape", YT.shape)
X.T, W.T, YT

X.T.shape (3, 1)
W.T.shape (4, 3)
YT.shape (4, 1)


(array([[5],
        [3],
        [6]]),
 array([[2, 0, 2],
        [1, 5, 5],
        [4, 3, 4],
        [3, 1, 0]]),
 array([[22],
        [50],
        [53],
        [18]]))